### ISSUE TITLE
Indent argument keys properly

### ISSUE THREAD

**Issue by mcandre** [Groovy-Emacs-Modes/groovy-emacs-modes#10]
Groovy autoindent mostly works, but when I press TAB for argument keys, Groovy mistakenly indents them to the far left column, rather than one level deep where they should be.

**Comment by russel** [comment]
Do you have an example code we can work with? We need to set up a proper set of tests and add something to cover this case to that set of tests.

**Comment by russel** [comment]
We have changed the Groovy mode from being a CC-Mode derived one to being a standalone one. We are therefore closing all issues relating to the old mode. If you try the new mode and see any problems please post a new issue.
