### ISSUE TITLE
groovy-mode cpu usage

### ISSUE THREAD

**Issue by philiparvidsson** [Groovy-Emacs-Modes/groovy-emacs-modes#106]
for whatever reason, groovy-mode spins one core up  to 100%

how to reproduce:

1. start emacs
2. install groovy-mode
3. open a groovy-file or enable groovy-mode
4. check cpu usage (there's a cmd.exe process maxing one core)

**Comment by Wilfred** [comment]
What process is running and maxing one core? Emacs itself, or something else?

**Comment by philiparvidsson** [comment]
This happens when I open a .groovy-file with groovy-mode:

![image](https://user-images.githubusercontent.com/1163299/35622955-ff2c7832-0689-11e8-85b2-944e2e47ff18.png)

It's a cmd.exe process.

**Comment by Wilfred** [comment]
I'm going to need more information to be able to debug this. What command is running under cmd.exe? I imagine you can see this with Windows tools, or `M-x list-processes` in Emacs might also be helpful.

**Comment by philiparvidsson** [comment]
This is the output of list-processes:

![image](https://user-images.githubusercontent.com/1163299/35732580-34770912-081a-11e8-8ffd-b38f83d5fa29.png)

If I disable flycheck-mode, the issues disappears. So maybe this is an issue with flycheck?

**Comment by Wilfred** [comment]
Yep, sounds like a flycheck issue. groovy-mode doesn't start any processes.
