### ISSUE TITLE
indentation error when string on prior line contains a keyword.

### ISSUE THREAD

**Issue by FormerPhysicist** [Groovy-Emacs-Modes/groovy-emacs-modes#126]
Like my prior issue, I've noticed that the indentation isn't right when a string contains a block keyword.  For example, 

```
def foo = "if for while else" 
	def bar = false // This isn't right

def foo = "normal string"
def bar = true // This is what I'd expect
```

I'll submit a PR shortly that should put this issue (I hope) to bed.

**Comment by djlindstr** [comment]
This is fixed, isn't it?

**Comment by Wilfred** [comment]
Yep.
