### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by cyberoblivion** [Groovy-Emacs-Modes/groovy-emacs-modes#149]
I'm running Fedora 36 and I've tried M-x customize but when I search for groovy nothing is returned.
Is there any rpm package or alternate installation instructions?

**Comment by Wilfred** [comment]
Oh, I can see why this is confusing. You need `M-x list-packages` to install new packages in Emacs, customize is just for configuring packages that you've already installed.

I've updated the readme.

**Comment by cyberoblivion** [comment]
I don't see with list-packages either.
![image](https://user-images.githubusercontent.com/1922839/177843356-0c0e2935-a75e-4165-8ea3-bfd0df6fadd0.png)

**Comment by Wilfred** [comment]
That looks like you haven't added MELPA to your sources of packages.

**Comment by cyberoblivion** [comment]
Yes, it's working now thanks!
