### ISSUE TITLE
Wrong indentation or wrong setup?

### ISSUE THREAD

**Issue by jordi-chacon** [Groovy-Emacs-Modes/groovy-emacs-modes#16]
Hi,

I just installed this mode (version 20150725.1050) and I get the following indentation:

```
g.traversal().V()
.method()
```

Shouldn't the second line be intended a few spaces to the left? If so, is this bug in the mode or maybe I have a setup that is messing things up?

Thanks

**Comment by jordi-chacon** [comment]
Another example of weird indentation:
```
    void a() {
        return new D(
            a: 1,
                     b: 2)
    }
```

**Comment by russel** [comment]
We need to get some tests in place for this mode and then add these examples to the set of tests.

**Comment by russel** [comment]
We have changed the Groovy mode from being a CC-Mode derived one to being a standalone one. We are therefore closing all issues relating to the old mode. If you try the new mode and see any problems please post a new issue.
