### ISSUE TITLE
Set indentation for groovy/grails mode

### ISSUE THREAD

**Issue by lifeisfoo** [Groovy-Emacs-Modes/groovy-emacs-modes#22]
I've tried using [this solution](http://stackoverflow.com/a/17838113/3340702) but it seems to work only sometimes. E.g. inside grails controllers methods, the tab size is always two...

How to set the indentation value for these modes?

**Comment by lifeisfoo** [comment]
I solved commenting [this line](https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/blob/master/groovy-mode.el#L626) in groovy-mode.el file.

**Comment by russel** [comment]
I would suggest that commenting out out that line will cause other errors. I think the solution has to be to take this use of : into account in the code of the `groovy-mode-fix-closure-with-argument` function.

**Comment by russel** [comment]
We have changed the Groovy mode from being a CC-Mode derived one to being a standalone one. We are therefore closing all issues relating to the old mode. If you try the new mode and see any problems please post a new issue.
