### ISSUE TITLE
request: improve detection of multi-line statements

### ISSUE THREAD

**Issue by dbyron0** [Groovy-Emacs-Modes/groovy-emacs-modes#23]
For code like this:

``` java
class Foo {
   public void bar() {
      int blah;
      int bar = blah
         .method1()
         .method2()
   }
}
```

when the cursor is on the lines with `.method1()` and `.method2()`, C-c C-o reveals that the current syntactic context is statement.  I'd love for groovy mode to recognize these as statement-cont so they're indented properly.  I can't tell if the issue is with [c-guess-basic-syntax](https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/blob/master/groovy-mode.el#L502) or [groovy-vsemi-p](https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/blob/master/groovy-mode.el#L242).

I'd love a hand confirming my understanding of the issue, and even better, a fix.

Thanks much.

-DB

**Comment by russel** [comment]
I believe this situation has been covered by changes in the past. I wonder if there is a bug in the code sample above in that there is a dot  after `blah` and before `method1`.

**Comment by dbyron0** [comment]
You're right there was an extra . above.  I've removed it.  Still get the same behavior though.

**Comment by russel** [comment]
Hummm… maybe it was the d-mode we sorted this issue in, and I thought we had fixed it in the groovy-mode. I'll have to see what can be done.

Though, if you find someone who can solve this and provide a pull request, that would be excellent.

**Comment by dbyron0** [comment]
Thanks.  I'm pretty sure my lisp skills are not up for this.  Or at least, even if it takes you awhile, I bet it still takes me a fair bit longer :(

**Comment by russel** [comment]
We have changed the Groovy mode from being a CC-Mode derived one to being a standalone one. We are therefore closing all issues relating to the old mode. If you try the new mode and see any problems please post a new issue.
