### ISSUE TITLE
Role out another version release

### ISSUE THREAD

**Issue by muralidcis** [Groovy-Emacs-Modes/groovy-emacs-modes#24]
@russel 

I download the version v-1.0.0. https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/releases/tag/v-1.0.0 end up with error: emacs Symbol's function definition is void: set-difference.(GNU Emacs 24.5.1)
How ever the files from you master seems to be working great, i think its high time you should role out another version release.

**Comment by russel** [comment]
I have tagged 1.0.1 in the repository, I hope this will generate an entry in MELPA Stable as well as causing Git to generate a release tarball.

**Comment by muralidcis** [comment]
Thanks, a lot, Amitha Buddha...

**Comment by russel** [comment]
Has version 1.0.1 worked for you?

**Comment by muralidcis** [comment]
It seems to be working fine, for me......

GNU Emacs 24.5.1  on Ubuntu 14.04.4 LTS

**Comment by russel** [comment]
@muralidcis Thanks. Now for the next problem… :-)
