### ISSUE TITLE
Variable types are not highlighted

### ISSUE THREAD

**Issue by Wilfred** [Groovy-Emacs-Modes/groovy-emacs-modes#27]
Given the following code:

``` groovy
def foo() {
    String x = 'foo'
    String y = 'foo'
    Thing z = new Thing()
    LinkedList otherLinked = [3, 4, 5]
    int num = 123
    String[] arrStr = ['Ananas', 'Banana', 'Kiwi']
}
```

![groovy_types](https://cloud.githubusercontent.com/assets/70800/18592419/e75a7724-7c04-11e6-8cfd-daca64be345a.png)

Most of the types are not highlighted. It looks like it's just the first type, plus any primitive types.

**Comment by russel** [comment]
We have changed the Groovy mode from being a CC-Mode derived one to being a standalone one. We are therefore closing all issues relating to the old mode. If you try the new mode and see any problems please post a new issue.
