### ISSUE TITLE
Incorrect highlighting of multiline strings containing ' and "

### ISSUE THREAD

**Issue by uzytkownik** [Groovy-Emacs-Modes/groovy-emacs-modes#29]
The groovy-mode treats incorrectly `'` and `"` as end of (respective) multi-line string.

**Comment by russel** [comment]
We have changed the Groovy mode from being a CC-Mode derived one to being a standalone one. We are therefore closing all issues relating to the old mode. If you try the new mode and see any problems please post a new issue.
