### ISSUE TITLE
'common' is incorrectly highlighted as keyword

### ISSUE THREAD

**Issue by Wilfred** [Groovy-Emacs-Modes/groovy-emacs-modes#33]
Given the code:

```groovy
def foo
def common
def bar
```

Groovy mode shows the following highlighting:

<img width="118" alt="screen shot 2017-03-01 at 15 13 49" src="https://cloud.githubusercontent.com/assets/70800/23465999/c2e35aae-fe91-11e6-9cca-142283392275.png">

It's applied `font-lock-type-face` to `common`. I'm not sure why, I can't see common listed in any keyword list in the code for groovy. It's also not a reserved word for C or Java as far as I can tell.

Any idea why this happens?

**Comment by russel** [comment]
We have changed the Groovy mode from being a CC-Mode derived one to being a standalone one. We are therefore closing all issues relating to the old mode. If you try the new mode and see any problems please post a new issue.
