### ISSUE TITLE
For standalone mode need specialisation document

### ISSUE THREAD

**Issue by russel** [Groovy-Emacs-Modes/groovy-emacs-modes#39]
With the CC Mode version of this mode documenting the ways of changing things like indent size etc. was (relatively) easy because it was a variant on java-mode, c++-mode, and c-mode.  Now it is not clear how to set these things. a short document setting out the user (re)settable values would be very handy.

**Comment by Wilfred** [comment]
Sure, I can write something. Where would you like it @russel ? In the README, or somewhere else?

FWIW, settings are organised under the groovy group, so `M-x customize` will list all the configurable options in the standalone groovy-mode.
