### ISSUE TITLE
Switch branches now?

### ISSUE THREAD

**Issue by russel** [Groovy-Emacs-Modes/groovy-emacs-modes#44]
I wonder if we are now at the stage where we take a maintenance branch of the CC mode version (version 1) and make standalone branch the master and declare it version 2. This leaves both version available but makes it clear the standalone version is the mainline.

**Comment by Wilfred** [comment]
Agreed! That gives a clear path for users and should get us more feedback on the standalone version.

**Comment by russel** [comment]
From what I can see, it is not going to be possible to switch branches as I had thought – I thought I had done this on another repository, but clearly I was misremembering. It is possible to do this for a local repository, but not a published (and thus cloned) one. The only way forward appears to be to create a wholly new repository with the correct branch structure, and then get everyone to switch to the new repository. I think the best b et might be to create emacs-groovy-modes repository with the new structure and then remove groovy-emacs-modes which will eventually cause people with clones to have a problem and this switch.

**Comment by russel** [comment]
I found a way of doing what was needed in a way that should do the right thing when people pull from the repository. It is possible that people will get very surprised when things break, so we have to be responsive. what was master is now 1.X, and what was standalone is now master. I'll check what happens with MELPA to ensure things are OK.

We should release 2.0.0 as soon as you are ready, so as to get something on MELPA Stable.
