### ISSUE TITLE
Update the personnel and docs

### ISSUE THREAD

**Issue by russel** [Groovy-Emacs-Modes/groovy-emacs-modes#45]
@Wilfred Perhaps you should update the groovy-mode.el to put yourself in as author?

Also we should do a serious updated of the commentary etc. to reflect the revolutionary change of the mode.

Moreover I wonder if a couple of examples of configuration for the init.el files might be in order?

**Comment by Wilfred** [comment]
In theory users shouldn't need to do anything to their init.el -- it should just work.
