### ISSUE TITLE
Doesn't even load

### ISSUE THREAD

**Issue by MarkSymsCtx** [Groovy-Emacs-Modes/groovy-emacs-modes#48]
The master branch (at commit f8e9628) fails to load

Debugger entered--Lisp error: (file-error "Cannot open load file" "s")
  require(s)
  eval-buffer(#<buffer  *load*-736134> nil "XXXXXXXXX/groovy-emacs-modes/groovy-mode.el" nil t)  ; Reading at buffer position 2657
  load-with-code-conversion("XXXXXXXXX/groovy-emacs-modes/groovy-mode.el" "XXXXXX/groovy-emacs-modes/groovy-mode.el" nil nil)
  load("groovy-mode")
  load-library("groovy-mode")
  (progn (load-library "groovy-mode") (setq auto-mode-alist (append (quote (("\\.groovy\\'" . groovy-mode) ("\\JenkinsFile" . groovy-mode))))) (add-hook (quote groovy-mode-hook) (quote (lambda nil (require (quote groovy-electric)) (groovy-electric-mode)))))
  (if (locate-library "groovy-mode") (progn (load-library "groovy-mode") (setq auto-mode-alist (append (quote (("\\.groovy\\'" . groovy-mode) ("\\JenkinsFile" . groovy-mode))))) (add-hook (quote groovy-mode-hook) (quote (lambda nil (require (quote groovy-electric)) (groovy-electric-mode))))))
  eval-buffer(#<buffer  *load*> nil "/XXXXXX/.emacs" nil t)  ; Reading at buffer position 5740
  load-with-code-conversion("/XXXXX/.emacs" "/XXXXX/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by russel** [comment]
That changeset is the current HEAD for the 1.X branch, not the master branch. I just tried it on Debian Sid with:

GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.12) of 2017-04-23, modified by Debian

and it "works for me".  If you wish to continue to use the old CC-Mode based Groovy Mode rather than the replacement, we will have to dig a bit deeper to see what it might be that is causing the problem. As a start could you let us know the context and the set up for the modes?

**Comment by MarkSymsCtx** [comment]
Sorry, pasted the wrong commit - I have 9849318 as the  HEAD of master and that's where I get the error. On CentOS 7.3.1611.

**Comment by MarkSymsCtx** [comment]
1.0.2 does load successfully and that's why I got the wrong commitish as I was having to jump between branches to allow emacs to even start up

**Comment by russel** [comment]
OK, that makes much more sense now :-) It looks like the Emacs you have does not have the s package. This is obtained via MELPA. (Actually I am not sure why we need that, but for now we do.)

**Comment by MarkSymsCtx** [comment]
ah right, that sorted it, I can at least load things now. I'll give it a try and see if it solves the issues we were seeing with the cc-mode version

**Comment by russel** [comment]
I think this version of the Groovy mode solves a number of the sticking points that were irritating people, but I have a suspicion there are some missing features that came with the CC_mode which will need to be re-created in this standalone version.
