### ISSUE TITLE
Got /bin/groovysh: No such file or directory` when running script

### ISSUE THREAD

**Issue by NaixiaoZhang** [Groovy-Emacs-Modes/groovy-emacs-modes#50]
When I run the script by "C-c C-s", I got an error:

`/usr/local/opt/emacs-plus/Emacs.app/Contents/MacOS/Emacs: /bin/groovysh: No such file or directory`

I install groovy by homebrew:

`brew install groovy`

Emacs version 26.0.50.

**Comment by russel** [comment]
This is strange, C-c C-s is undefined for me!

**Comment by NaixiaoZhang** [comment]
I checked the help doc by `C-h m`. It shows

`C-c C-s         run-groovy`

**Comment by NaixiaoZhang** [comment]
@russel you're right. I've set the "JAVA_HOME" and "GROOVY_HOME" in the `config.fish`. And Emacs can't find the "GROOVY_HOME" if I start it from Launchpad. But Emacs can find them if I start it from terminal. 

Do you know how emacs can read the environment variables if start from launchpad? 
I know this question should be asked to Emacs group/irc...

**Comment by russel** [comment]
I have a putative solution to this to try and find groovysh on the user path even without GROOVY_PATH set. I shall take the risk of comitting this. This will trigger a MELPA rebuild, let's hope it works.

**Comment by russel** [comment]
@NaixiaoZhang I think MELPA now has the new version of inf-groovy.el so an update and try again might show the fix works or doesn't.

**Comment by NaixiaoZhang** [comment]
@russel I just did an update. It has been fixed!
For now, no matter the GROOVY_HOME is defined or not, launch from Launchpad or terminal can both work. Perfect!

**Comment by russel** [comment]
Splendid. :-) Let's treat this as fixed for now and close this issue. If there are other problems let's do it via other issues.
