### ISSUE TITLE
Melpa is installing the old package by default

### ISSUE THREAD

**Issue by vincekd** [Groovy-Emacs-Modes/groovy-emacs-modes#63]
I'm installing from melpa. Looks like that installs the old version by default?
From `package-list-packages`

```
groovy-mode        201203310931  installed             Groovy mode derived mode
```

The newer versions are marked as obsolete:

```
groovy-mode        20170323.817  obsolete              Major mode for Groovy source files
groovy-mode        20170503.148  obsolete              Major mode for Groovy source files
groovy-mode        20170516.1155 obsolete              Major mode for Groovy source files
```

Probably because the old version is missing a `.` between date and version.

**Comment by vincekd** [comment]
Never mind, deleting my elpa folder and letting it re-fetch fixed the issue. Sorry to bother you!

**Comment by russel** [comment]
Thanks for sorting out the fix as well as submitting the issue. :-)

I hadn't seen that problem before so it is good to know of it, and what the first step is to try to fix it.
