### ISSUE TITLE
wrong command in groovy-load-file

### ISSUE THREAD

**Issue by ax006ho** [Groovy-Emacs-Modes/groovy-emacs-modes#68]
AFAIK there are two issues in inf-groovy.el. 
1. line 140 is doubled
2. commands in the groovysh are abbreviated with a starting colon, not a backslash
I attach a patch which solves these issues. On Linux it can be applied by

 patch inf-groovy.el -i 00diff.txt
[00diff.txt](https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/files/1116398/00diff.txt)
 -o inf-groovy.el.new

followed by 

mv inf-groovy.el.new  inf-groovy.el

I would appreciate this patch being applied in the repository and not on my local machine.

Thanks in advance and thank you for providing groovy-emacs-mode!

Jobst Hoffmann

**Comment by russel** [comment]
@ax006ho Any chance of doing this change as a pull request?

**Comment by ax006ho** [comment]
I did it, I hope you can use it.

**Comment by Wilfred** [comment]
Closed in #69.
