### ISSUE TITLE
cl-macroexpand-all is void

### ISSUE THREAD

**Issue by kaidamasaki** [Groovy-Emacs-Modes/groovy-emacs-modes#7]
It looks like `cl-macroexpand-all` has been renamed `macroexpand-all` in emacs 24.3.

This causes groovy-mode to fail to load.

**Comment by russel** [comment]
I am not seeing a problem of this sort in 24.5.1 on Debian Sid. I shall close this now, please reopen if this specific problem is not fixed as it is believed to be.
