### ISSUE TITLE
How do we implement groovy-mode from MELPA for .gradle files?

### ISSUE THREAD

**Issue by sammyjava** [Groovy-Emacs-Modes/groovy-emacs-modes#73]
Terribly newby question here, but I haven't used MELPA in the past, and I had no luck trying to load your groovy-mode.el file the normal way that I've done others under emacs.d/lisp/groovy-mode.

I've got this at the bottom of my .emacs:
```
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
```
What perchance do I do in addition to get my .gradle files to syntax highlight in groovy-mode? Thanks!

**Comment by sammyjava** [comment]
Oh, Lord, sometimes my age is telling. Thanks! Now my emacs world has changed. (I will admit that most of the modes I use are loadable from the Fedora/Ubuntu repos,  so I haven't delved into front-line modes much.) There is, in fact, a gradle-mode in there from some source, and it appears to be crap; your groovy-mode is the way to go.

Turning this into a minor actual issue, there were warnings issued when I installed groovy-mode, none of which seem to have any effect as far as syntax highlighting and tabbing.

Thanks for getting me up to date on emacs mode installing!
```
Leaving directory `/home/sam/.emacs.d/elpa/s-20170428.1026'

Compiling file /home/sam/.emacs.d/elpa/s-20170428.1026/s-pkg.el at Mon Jul 24 07:02:57 2017
Entering directory `/home/sam/.emacs.d/elpa/s-20170428.1026/'

Compiling file /home/sam/.emacs.d/elpa/s-20170428.1026/s.el at Mon Jul 24 07:02:57 2017

Compiling no file at Mon Jul 24 07:03:00 2017
Leaving directory `/home/sam/.emacs.d/elpa/gradle-mode-20150313.1205'

Compiling file /home/sam/.emacs.d/elpa/gradle-mode-20150313.1205/gradle-mode-pkg.el at Mon Jul 24 07:03:00 2017
Entering directory `/home/sam/.emacs.d/elpa/gradle-mode-20150313.1205/'

Compiling file /home/sam/.emacs.d/elpa/gradle-mode-20150313.1205/gradle-mode.el at Mon Jul 24 07:03:00 2017

Compiling no file at Mon Jul 24 07:05:32 2017
Leaving directory `/home/sam/.emacs.d/elpa/groovy-mode-201203310931'

Compiling file /home/sam/.emacs.d/elpa/groovy-mode-201203310931/groovy-mode-pkg.el at Mon Jul 24 07:05:32 2017
Entering directory `/home/sam/.emacs.d/elpa/groovy-mode-201203310931/'

Compiling file /home/sam/.emacs.d/elpa/groovy-mode-201203310931/groovy-mode.el at Mon Jul 24 07:05:32 2017

In groovy-lineup-arglist:
groovy-mode.el:437:38:Warning: reference to free variable
    `c-syntactic-element'

In groovy-mode:
groovy-mode.el:566:25:Warning: (lambda nil ...) quoted with ' rather than with
    #'
groovy-mode.el:566:25:Warning: (lambda nil ...) quoted with ' rather than with
    #'

In end of data:
groovy-mode.el:592:1:Warning: the function `c-populate-syntax-table' might not
    be defined at runtime.
```

**Comment by russel** [comment]
I would advise getting Emacs itself from packages and uninstalling all OS Emacs packages. Getting all Emacs packages from ELPA and MELPA is the way to go.

As for the bug/issue, I suggest posting it to a new issue and that we close this one. We could change the title on this issue but then we would have two threads operating in the same issue, and it is best for each issue to be a single thread. Is that OK for you?

**Comment by sammyjava** [comment]
Indeed, sorry about the thread-jack. :) Closing this one, thanks again!
