### ISSUE TITLE
/* foo */ is treated as a slashy-string

### ISSUE THREAD

**Issue by Wilfred** [Groovy-Emacs-Modes/groovy-emacs-modes#75]
This should be highlighted as a string. Possibly related to #74, but we should have a test for this too.

**Comment by vincekd** [comment]
@Wilfred did you mean "should be highlighted as a string" or shouldn't as it's a comment?

**Comment by Wilfred** [comment]
@vincekd oops, sorry. `/* foo */` should *not* be highlighted as a string, but should be highlighted as a comment. Currently it's highlighted as a string.

**Comment by Wilfred** [comment]
I've just grabbed the latest version of master and it is highlighting `/* foo */` correctly, so your unit test is now all that we need :)
