### ISSUE TITLE
Closure indentation on 20170808.1211

### ISSUE THREAD

**Issue by jordi-chacon** [Groovy-Emacs-Modes/groovy-emacs-modes#83]
This is how `20170808.1211` currently indents closures:
```
class A {
    def foo() {
        [1, 2, 3]
            .findAll {
            it % 2 == 0
        }
            .collect { it ->
            it + 1
        }
    }
}
```

And I would say this is how it should be:
```
class A {
    def foo() {
        [1, 2, 3]
            .findAll {
                it % 2 == 0
            }
            .collect { it ->
                it + 1
            }
    }
}
```

**Comment by Wilfred** [comment]
This is actually the same issue as #61, but I've decided to close that big issue in favour of this one, which is smaller and clearer.

**Comment by Wilfred** [comment]
(The issue here is that we don't always consider `.foo` to increase the indentation depth. This breaks nested `.foo` too.)

**Comment by mariogarcia** [comment]
Anything new on this ? I'm suffering this problem too.

**Comment by haqle314** [comment]
> (The issue here is that we don't always consider `.foo` to increase the indentation depth. This breaks nested `.foo` too.)

I don't have much experience with Groovy so I'm not sure what you're talking about here. Could you give some example code for the cases you mentioned? As far as I understand, just adding 1 indentation level when the current line has `.foo {` but no matching `}` should suffice, correct?
