### ISSUE TITLE
Parameterized types do not highlight variable name

### ISSUE THREAD

**Issue by vincekd** [Groovy-Emacs-Modes/groovy-emacs-modes#85]
`List list` works fine, correctly highlighting list, however `List<Map> list` doesn't highlight list at all.

![screenshot_20170809_202712](https://user-images.githubusercontent.com/641433/29149279-271ddbec-7d41-11e7-9cd7-073f0b6315ad.png)

**Comment by Wilfred** [comment]
This is currently done by `groovy-declaration-regexp`. Nesting parens can't be done with a regular expression, so we'd need to write an elisp function.
