### ISSUE TITLE
The run-groovy command assumes groovysh in /bin

### ISSUE THREAD

**Issue by mattiasb** [Groovy-Emacs-Modes/groovy-emacs-modes#89]
Hi!

The `run-groovy` interactive command assumes `groovysh` to reside in `/bin/`. This isn't the case in Ubuntu where it instead sits in `/usr/bin/`.

It would be great if:
1. the `groovy-program-name` variable was made customizable through `customize`
2. the `groovy-program-name` included the full path
3. The default behaviour was to search for the executable with `executable-find` for minimum needed configuration. See [here](https://github.com/racer-rust/emacs-racer/blob/master/racer.el#L77-L83) for how `emacs-racer` does this.

**Comment by Wilfred** [comment]
Please upgrade. `groovysh` is now a customizable variable that uses the full path and `executable-find`, so I think we do all of those now :)

**Comment by mattiasb** [comment]
You are correct. Sorry for the noise and thanks for the great mode!
