### ISSUE TITLE
treat groovy-mode as a prog-mode

### ISSUE THREAD

**Issue by mcandre** [Groovy-Emacs-Modes/groovy-emacs-modes#9]
Please configure groovy-mode so that it is considered a prog-mode, like c-mode, javascript-mode, ruby-mode, etc., so that tools like whitespace-mode can autoload for Groovy code.

**Comment by russel** [comment]
As far as I am aware, the define-derived-mode call uses prog-mode if that is defined in the Emacs being used. cf. https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/blob/master/groovy-mode.el#L602

**Comment by russel** [comment]
I am closing this issue as I think it is not an issue. Please reopen if I am mistaken on this.

**Comment by vincekd** [comment]
I'm also having this issue, where the `prog-mode-hook` does not fire for `groovy-mode` and so a bunch of minor modes don't get loaded. I'm on `emacs 25.2.1`. I can't figure out what isn't working here.

**Comment by russel** [comment]
@vincekd Which Groovy mode are you using? Since the Groovy mode has undergone a revolutionary change since this issue was posted I think it might be best to open a new issue if you are seeing problems.
