### ISSUE TITLE
String interpolation syntax highlighted in single-quoted strings

### ISSUE THREAD

**Issue by bgamari** [Groovy-Emacs-Modes/groovy-emacs-modes#90]
Groovy-mode appears to highlight instances of string interpolation syntax in single-quoted string literals (e.g. `'hello ${world}') despite the fact that AFAIK string interpolation is not performed in such literals.

**Comment by Wilfred** [comment]
Thanks, we didn't handle this particular type of interpolation correctly. It should be fixed now.
