### ISSUE TITLE
not: Symbol's function definition is void: s-blank-str\?

### ISSUE THREAD

**Issue by MarkSymsCtx** [Groovy-Emacs-Modes/groovy-emacs-modes#96]
When using tab to indent (which fails), I see the message

`not: Symbol's function definition is void: s-blank-str\?`

in the Messages buffer.

Using 36cd834 from git@github.com:Groovy-Emacs-Modes/groovy-emacs-modes.git

Tried this with a locally entered copy of the RomanDigits enum on the README page.

**Comment by Wilfred** [comment]
Please update your version of s.el. I imagine that will fix it :)

**Comment by MarkSymsCtx** [comment]
I have 1.11.0 (which seems to be the latest available).

**Comment by Wilfred** [comment]
Would you mind installing the latest version from MELPA? It looks like s.el on MELPA Stable doesn't have this function.

I've filed https://github.com/magnars/s.el/issues/114 to request a new release.

**Comment by Wilfred** [comment]
1.12.0 is out, and I've updated groovy-mode to depend on this version. Thanks for the report!

**Comment by MarkSymsCtx** [comment]
Confirmed, that fixed it.
